# Generated by Django 5.1.3 on 2025-03-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionResidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('residencia', models.CharField(max_length=255)),
                ('coordenadas', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Distribución por Residencia',
                'verbose_name_plural': 'Distribuciones por Residencia',
                'ordering': ['residencia'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Preparatoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Bachillerato', 'Bachillerato'), ('Tecnica', 'Técnica'), ('Oficial', 'Oficial'), ('Tecnologico', 'Tecnológico')], max_length=20)),
            ],
            options={
                'verbose_name': 'Preparatoria',
                'verbose_name_plural': 'Preparatorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['usuario_id'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('residencia', models.CharField(max_length=255)),
                ('trabaja', models.BooleanField(default=False)),
                ('trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera')),
                ('preparatoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.preparatoria')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_egreso', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Egresado',
                'verbose_name_plural': 'Egresados',
                'ordering': ['fecha_egreso'],
            },
        ),
        migrations.CreateModel(
            name='EstudianteDiscapacidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_discapacidad', models.CharField(max_length=255)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Discapacidad del Estudiante',
                'verbose_name_plural': 'Discapacidades de Estudiantes',
                'ordering': ['estudiante'],
            },
        ),
        migrations.CreateModel(
            name='EstudianteTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_trabajo', models.CharField(max_length=255)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Trabajo del Estudiante',
                'verbose_name_plural': 'Trabajos de Estudiantes',
                'ordering': ['estudiante'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Evaluación Docente',
                'verbose_name_plural': 'Evaluaciones Docentes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cuatrimestre', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['cuatrimestre'],
            },
        ),
        migrations.CreateModel(
            name='DocenteMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
            ],
            options={
                'verbose_name': 'Docente-Materia',
                'verbose_name_plural': 'Docentes-Materias',
                'unique_together': {('docente', 'materia')},
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='materias',
            field=models.ManyToManyField(through='api.DocenteMateria', to='api.materia'),
        ),
        migrations.CreateModel(
            name='MotivoAbandono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_abandono', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('comentarios', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Motivo de Abandono',
                'verbose_name_plural': 'Motivos de Abandono',
                'ordering': ['fecha_abandono'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Cuatrimestre', 'Cuatrimestre'), ('Anual', 'Anual')], max_length=20)),
                ('anio', models.IntegerField()),
                ('numero', models.IntegerField(help_text='Número de cuatrimestre o año (1, 2, 3, ...)')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['anio', 'numero'],
                'unique_together': {('tipo', 'anio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuatrimestre', models.IntegerField()),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['carrera', 'cuatrimestre'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionResumen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuatrimestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('calificaciones', models.DecimalField(decimal_places=2, max_digits=4)),
                ('aprobados', models.IntegerField()),
                ('reprobados', models.IntegerField()),
                ('promedio_cuatrimestral', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promedio_anual', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'verbose_name': 'Evaluación Resumen',
                'verbose_name_plural': 'Evaluaciones Resumen',
                'ordering': ['estudiante', 'periodo'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha', models.DateField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TiempoFinalizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('duracion_carrera', models.IntegerField(help_text='Duración en meses')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'verbose_name': 'Tiempo de Finalización',
                'verbose_name_plural': 'Tiempos de Finalización',
                'ordering': ['duracion_carrera'],
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
        migrations.CreateModel(
            name='DistribucionEdad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
            ],
            options={
                'verbose_name': 'Distribución por Edad',
                'verbose_name_plural': 'Distribuciones por Edad',
                'ordering': ['edad', 'carrera'],
                'unique_together': {('edad', 'carrera')},
            },
        ),
        migrations.CreateModel(
            name='DistribucionEdadCarrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
            ],
            options={
                'verbose_name': 'Distribución Edad por Carrera',
                'verbose_name_plural': 'Distribuciones Edad por Carrera',
                'ordering': ['carrera', 'edad'],
                'unique_together': {('carrera', 'edad')},
            },
        ),
        migrations.CreateModel(
            name='DistribucionEstudiantesCuatrimestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrera')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'verbose_name': 'Distribución Estudiantes por Cuatrimestre',
                'verbose_name_plural': 'Distribuciones Estudiantes por Cuatrimestre',
                'ordering': ['carrera', 'periodo'],
                'unique_together': {('carrera', 'periodo')},
            },
        ),
    ]
