# Generated by Django 5.1.3 on 2025-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
