# Generated by Django 5.1.7 on 2025-04-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('anio', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('clave', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativoAntiguo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativoNuevo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='CicloPeriodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloescolar')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'unique_together': {('ciclo', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='IndicadoresGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desertores', models.IntegerField()),
                ('reprobados', models.IntegerField()),
                ('egresados', models.IntegerField()),
                ('ciclo_periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaPorGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hombres', models.IntegerField(default=0)),
                ('mujeres', models.IntegerField(default=0)),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
            ],
        ),
        migrations.CreateModel(
            name='NuevoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.IntegerField(default=0)),
                ('renoes', models.IntegerField(default=0)),
                ('uaem_gem', models.IntegerField(default=0)),
                ('pase_directo', models.IntegerField(default=0)),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaPorCuatrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaNuevoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='GeneracionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('ingreso_hombres', models.IntegerField(default=0)),
                ('ingreso_mujeres', models.IntegerField(default=0)),
                ('egresados_cohorte_h', models.IntegerField(default=0)),
                ('egresados_cohorte_m', models.IntegerField(default=0)),
                ('egresados_rezagados_h', models.IntegerField(default=0)),
                ('egresados_rezagados_m', models.IntegerField(default=0)),
                ('titulados_h', models.IntegerField(default=0)),
                ('titulados_m', models.IntegerField(default=0)),
                ('registrados_dgp_h', models.IntegerField(default=0)),
                ('registrados_dgp_m', models.IntegerField(default=0)),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
            options={
                'verbose_name': 'Generación por Carrera',
                'verbose_name_plural': 'Generaciones por Carrera',
                'ordering': ['fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='EficienciaTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.IntegerField()),
                ('matricula_ingreso', models.IntegerField()),
                ('egresados', models.IntegerField()),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='AprovechamientoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ciclo_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cicloperiodo')),
                ('programa_antiguo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativoantiguo')),
                ('programa_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.programaeducativonuevo')),
            ],
        ),
    ]
