# Generated by Django 5.1.7 on 2025-04-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditosEstudiantePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditos_aprobados', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.periodo')),
            ],
            options={
                'verbose_name': 'Créditos por Estudiante y Periodo',
                'verbose_name_plural': 'Créditos por Estudiante y Periodo',
                'ordering': ['estudiante', 'periodo'],
                'unique_together': {('estudiante', 'periodo')},
            },
        ),
    ]
