# Generated by Django 5.2 on 2025-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cicloescolar_id_alter_cicloescolar_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cicloescolar',
            name='id',
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='anio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
